export const PERMISSIONS = [
  'company.create',
  'company.view',
  'company.update',
  'company.delete',
  'company.suspend',
  'company.activate',
  'plan.create',
  'plan.view',
  'plan.update',
  'plan.delete',
  'subscription.create',
  'subscription.view',
  'subscription.update',
  'subscription.cancel',
  'user.create',
  'user.view',
  'user.update',
  'user.delete',
  'role.create',
  'role.view',
  'role.update',
  'role.delete',
  'customer.create',
  'customer.view',
  'customer.update',
  'customer.delete',
  'supplier.create',
  'supplier.view',
  'supplier.update',
  'supplier.delete',
  'product.create',
  'product.view',
  'product.update',
  'product.delete',
  'category.create',
  'category.view',
  'category.update',
  'category.delete',
  'unit.create',
  'unit.view',
  'unit.update',
  'unit.delete',
  'employee.create',
  'employee.view',
  'employee.update',
  'employee.delete',
  'chamber.create',
  'chamber.view',
  'chamber.update',
  'chamber.delete',
  'rack.create',
  'rack.view',
  'rack.update',
  'rack.delete',
  'location.create',
  'location.view',
  'location.update',
  'location.delete',
  'inventory.view',
  'inventory.adjust',
  'inventory.transfer',
  'batch.create',
  'batch.view',
  'batch.update',
  'batch.delete',
  'inward.create',
  'inward.view',
  'inward.update',
  'inward.cancel',
  'outward.create',
  'outward.view',
  'outward.update',
  'outward.cancel',
  'invoice.create',
  'invoice.view',
  'invoice.update',
  'invoice.delete',
  'payment.create',
  'payment.view',
  'payment.delete',
  'ledger.view',
  'expense.create',
  'expense.view',
  'expense.update',
  'expense.delete',
  'vehicle.create',
  'vehicle.view',
  'vehicle.update',
  'vehicle.delete',
  'driver.create',
  'driver.view',
  'driver.update',
  'driver.delete',
  'gate.create',
  'gate.view',
  'gate.update',
  'weighment.create',
  'weighment.view',
  'quality.create',
  'quality.view',
  'rental.view',
  'rental.update',
  'report.view',
  'report.export',
  'settings.view',
  'settings.update',
  'audit.view',
  'notification.view',
  'document.view',
  'document.upload',
] as const;

export type PermissionKey = (typeof PERMISSIONS)[number];

export const ROLE_CODES = {
  SUPER_ADMIN: 'super_admin',
  COMPANY_ADMIN: 'company_admin',
  MANAGER: 'manager',
  ACCOUNTANT: 'accountant',
  WAREHOUSE_STAFF: 'warehouse_staff',
  GATE_STAFF: 'gate_staff',
} as const;

export type RoleCode = (typeof ROLE_CODES)[keyof typeof ROLE_CODES];

export const COMPANY_STATUSES = ['active', 'suspended', 'trial', 'deleted'] as const;
export const SUBSCRIPTION_STATUSES = ['trial', 'active', 'expired', 'suspended', 'cancelled'] as const;
export const USER_STATUSES = ['active', 'suspended', 'pending'] as const;
export const BILLING_CYCLES = ['monthly', 'yearly'] as const;
export const MASTER_STATUSES = ['active', 'inactive'] as const;
export const INVENTORY_STATUSES = ['available', 'reserved', 'blocked', 'damaged', 'released'] as const;
export const STOCK_TXN_TYPES = [
  'OPENING',
  'INWARD',
  'OUTWARD',
  'TRANSFER_IN',
  'TRANSFER_OUT',
  'ADJUSTMENT_IN',
  'ADJUSTMENT_OUT',
  'DAMAGE',
  'REVERSAL',
] as const;
export const INWARD_STATUSES = ['draft', 'pending', 'received', 'allocated', 'completed', 'cancelled'] as const;
export const OUTWARD_STATUSES = ['draft', 'requested', 'approved', 'picking', 'ready', 'dispatched', 'completed', 'cancelled'] as const;
export const INVOICE_STATUSES = ['issued', 'cancelled'] as const;

export const DEFAULT_PAGE = 1;
export const DEFAULT_LIMIT = 20;
export const MAX_LIMIT = 100;
